use crate::error::Result;

/// Validates and fixes literature note content generated by LLM.
///
/// This ensures proper structure even when models fail to follow formatting
/// instructions (common with smaller local models).
pub struct LiteratureNoteProcessor;

impl LiteratureNoteProcessor {
    /// Validate and fix the generated note content.
    ///
    /// # Arguments
    ///
    /// * `content` - Raw content from LLM
    /// * `source_title` - Title of the source material
    /// * `source_path` - Path to the source file
    ///
    /// # Returns
    ///
    /// Fixed content with guaranteed frontmatter and structure.
    pub fn validate_and_fix(
        content: &str,
        source_title: &str,
        source_path: &str,
    ) -> Result<String> {
        let mut fixed = content.to_string();

        // 1. Ensure frontmatter exists and is correct
        // Some LLMs may generate frontmatter with incorrect source paths
        if fixed.starts_with("---\n") {
            // Extract existing frontmatter
            if let Some(end_pos) = fixed.find("\n---\n") {
                let frontmatter = &fixed[..end_pos + 4]; // includes closing ---
                let body = &fixed[end_pos + 5..]; // after closing ---

                // Check if source field exists and is correct
                let source_field = format!("source: {}", source_path);
                if !frontmatter.contains("source:") {
                    // Add source field
                    fixed = format!(
                        "---\ntype: literature\n{}\n---\n{}",
                        source_field,
                        body.trim_start()
                    );
                } else if !frontmatter.contains(source_field.as_str()) {
                    // Replace incorrect source
                    // Find and replace the source line
                    let lines: Vec<&str> = frontmatter.lines().collect();
                    let mut new_lines = Vec::new();
                    for line in lines {
                        if line.starts_with("source:") {
                            new_lines.push(source_field.as_str());
                        } else {
                            new_lines.push(line);
                        }
                    }
                    fixed = format!("{}\n---\n{}", new_lines.join("\n"), body.trim_start());
                }
                // else source is correct, keep as-is
            }
        } else {
            // No frontmatter, add it
            fixed = format!(
                "---\ntype: literature\nsource: {}\n---\n\n{}",
                source_path,
                fixed.trim()
            );
        }

        // 2. Ensure title exists
        if !fixed.contains("# ") && !fixed.contains("## ") {
            fixed = format!("# {}\n\n{}", source_title, fixed);
        }

        // 3. Normalize wiki-links
        fixed = Self::normalize_wiki_links(&fixed);

        // 4. Remove excessive whitespace
        fixed = Self::normalize_whitespace(&fixed);

        // Note: We do NOT truncate the content. If the LLM generates a long note,
        // it's better to keep it complete than to lose information. The prompt
        // should guide the LLM to be concise, but we don't force-truncate.

        Ok(fixed)
    }

    /// Normalize wiki-link formatting.
    ///
    /// Fixes common formatting issues:
    /// - `[[link] ]` → `[[link]]`
    /// - `[ [link]]` → `[[link]]`
    fn normalize_wiki_links(content: &str) -> String {
        let mut result = content.to_string();

        // Fix spaces inside brackets
        result = result.replace("[[ ", "[[");
        result = result.replace(" ]]", "]]");

        // Fix spaces around pipe in labeled links
        result = result.replace(" |", "|");
        result = result.replace("| ", "|");

        result
    }

    /// Remove excessive blank lines and trim content.
    fn normalize_whitespace(content: &str) -> String {
        let lines: Vec<&str> = content.lines().collect();
        let mut result = String::new();
        let mut prev_blank = false;

        for line in lines {
            let is_blank = line.trim().is_empty();

            // Skip multiple consecutive blank lines
            if is_blank && prev_blank {
                continue;
            }

            result.push_str(line);
            result.push('\n');

            prev_blank = is_blank;
        }

        result.trim().to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_validate_and_fix_adds_frontmatter() {
        let content = "# Test\n\nSome content";
        let result =
            LiteratureNoteProcessor::validate_and_fix(content, "Test Title", "raw/test.md")
                .unwrap();

        assert!(result.starts_with("---\n"));
        assert!(result.contains("type: literature"));
        assert!(result.contains("source: raw/test.md"));
        assert!(!result.contains("[... truncated"));
    }

    #[test]
    fn test_validate_and_fix_preserves_existing_frontmatter() {
        let content = "---\ntype: literature\nsource: raw/test.md\n---\n\n# Test";
        let result =
            LiteratureNoteProcessor::validate_and_fix(content, "Test Title", "raw/test.md")
                .unwrap();

        assert!(result.starts_with("---\ntype: literature"));
        assert!(!result.contains("[... truncated"));
    }

    #[test]
    fn test_validate_and_fix_corrects_wrong_source() {
        let content = "---\ntype: literature\nsource: wrong/path.md\n---\n\n# Test";
        let result =
            LiteratureNoteProcessor::validate_and_fix(content, "Test Title", "raw/correct.md")
                .unwrap();

        assert!(result.contains("source: raw/correct.md"));
        assert!(!result.contains("wrong/path.md"));
    }

    #[test]
    fn test_validate_and_fix_adds_missing_source() {
        let content = "---\ntype: literature\n---\n\n# Test";
        let result =
            LiteratureNoteProcessor::validate_and_fix(content, "Test Title", "raw/test.md")
                .unwrap();

        assert!(result.contains("source: raw/test.md"));
    }

    #[test]
    fn test_normalize_wiki_links_fixes_spaces() {
        let content = "See [[link ]] and [[test | label]]";
        let result = LiteratureNoteProcessor::normalize_wiki_links(content);

        // The function fixes spaces inside brackets and around pipes
        assert!(!result.contains("[[ "));
        assert!(!result.contains(" ]]"));
        assert!(!result.contains("| "));
    }

    #[test]
    fn test_normalize_whitespace_removes_extra_blanks() {
        let content = "Line 1\n\n\n\nLine 2\n\n\n";
        let result = LiteratureNoteProcessor::normalize_whitespace(&content);

        assert!(!result.contains("\n\n\n"));
        assert!(result.ends_with("Line 2"));
    }

    #[test]
    fn test_validate_and_fix_adds_title_if_missing() {
        let content = "Just some text without headers";
        let result =
            LiteratureNoteProcessor::validate_and_fix(content, "My Source", "raw/source.md")
                .unwrap();

        assert!(result.contains("# My Source"));
    }

    #[test]
    fn test_validate_and_fix_no_truncation() {
        let long_content = format!(
            "---\ntype: literature\nsource: raw/test.md\n---\n\n# Test\n\n{}",
            "word ".repeat(1000)
        );
        let result =
            LiteratureNoteProcessor::validate_and_fix(&long_content, "Test Title", "raw/test.md")
                .unwrap();

        // Should NOT truncate even very long content
        assert!(!result.contains("[... truncated"));
        assert!(result.len() > 5000); // Should be much longer than any cap
    }
}
