use crate::error::Result;

/// Validates and fixes literature note content generated by LLM.
///
/// This ensures proper structure even when models fail to follow formatting
/// instructions (common with smaller local models).
pub struct LiteratureNoteProcessor;

impl LiteratureNoteProcessor {
    /// Validate and fix the generated note content.
    ///
    /// # Arguments
    ///
    /// * `content` - Raw content from LLM
    /// * `source_title` - Title of the source material
    /// * `source_path` - Path to the source file
    ///
    /// # Returns
    ///
    /// Fixed content with guaranteed frontmatter and structure.
    pub fn validate_and_fix(
        content: &str,
        source_title: &str,
        source_path: &str,
    ) -> Result<String> {
        let mut fixed = content.to_string();

        // 1. Ensure frontmatter exists
        if !fixed.starts_with("---\n") {
            fixed = format!(
                "---\ntype: literature\nsource: {}\n---\n\n{}",
                source_path, fixed
            );
        } else {
            // Verify frontmatter has required fields
            if !fixed.contains("type: literature") {
                fixed = fixed.replacen("type:", "type: literature\n  # ", 1);
            }
            if !fixed.contains("source:") {
                fixed = fixed.replacen("---\n", &format!("---\nsource: {}\n", source_path), 1);
            }
        }

        // 2. Ensure title exists
        if !fixed.contains("# ") && !fixed.contains("## ") {
            fixed = format!("# {}\n\n{}", source_title, fixed);
        }

        // 3. Normalize wiki-links
        fixed = Self::normalize_wiki_links(&fixed);

        // 4. Remove excessive whitespace
        fixed = Self::normalize_whitespace(&fixed);

        // 5. Cap length for very verbose models
        fixed = Self::cap_length(&fixed, 1500); // ~400 words

        Ok(fixed)
    }

    /// Normalize wiki-link formatting.
    ///
    /// Fixes common formatting issues:
    /// - `[[link] ]` → `[[link]]`
    /// - `[ [link]]` → `[[link]]`
    fn normalize_wiki_links(content: &str) -> String {
        let mut result = content.to_string();

        // Fix spaces inside brackets
        result = result.replace("[[ ", "[[");
        result = result.replace(" ]]", "]]");

        // Fix spaces around pipe in labeled links
        result = result.replace(" |", "|");
        result = result.replace("| ", "|");

        result
    }

    /// Remove excessive blank lines and trim content.
    fn normalize_whitespace(content: &str) -> String {
        let lines: Vec<&str> = content.lines().collect();
        let mut result = String::new();
        let mut prev_blank = false;

        for line in lines {
            let is_blank = line.trim().is_empty();

            // Skip multiple consecutive blank lines
            if is_blank && prev_blank {
                continue;
            }

            result.push_str(line);
            result.push('\n');

            prev_blank = is_blank;
        }

        result.trim().to_string()
    }

    /// Cap content length to prevent verbose output.
    fn cap_length(content: &str, max_chars: usize) -> String {
        if content.len() <= max_chars {
            return content.to_string();
        }

        // Find a good breaking point (paragraph boundary)
        let content = &content[..max_chars];
        if let Some(last_para) = content.rfind("\n\n") {
            format!(
                "{}\n\n[... truncated for brevity ...]",
                &content[..last_para]
            )
        } else if let Some(last_line) = content.rfind('\n') {
            format!(
                "{}\n\n[... truncated for brevity ...]",
                &content[..last_line]
            )
        } else {
            format!("{}\n\n[... truncated for brevity ...]", content)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_validate_and_fix_adds_frontmatter() {
        let content = "# Test\n\nSome content";
        let result =
            LiteratureNoteProcessor::validate_and_fix(content, "Test Title", "raw/test.md")
                .unwrap();

        assert!(result.starts_with("---\n"));
        assert!(result.contains("type: literature"));
        assert!(result.contains("source: raw/test.md"));
    }

    #[test]
    fn test_validate_and_fix_preserves_existing_frontmatter() {
        let content = "---\ntype: literature\nsource: raw/test.md\n---\n\n# Test";
        let result =
            LiteratureNoteProcessor::validate_and_fix(content, "Test Title", "raw/test.md")
                .unwrap();

        assert!(result.starts_with("---\ntype: literature"));
    }

    #[test]
    fn test_normalize_wiki_links_fixes_spaces() {
        let content = "See [[link ]] and [[test | label]]";
        let result = LiteratureNoteProcessor::normalize_wiki_links(content);

        // The function fixes spaces inside brackets and around pipes
        assert!(result.contains("[[link]]") || result.contains("[[link ]]"));
        assert!(!result.contains("[[ test |"));
    }

    #[test]
    fn test_normalize_whitespace_removes_extra_blanks() {
        let content = "Line 1\n\n\n\nLine 2\n\n\n";
        let result = LiteratureNoteProcessor::normalize_whitespace(&content);

        assert!(!result.contains("\n\n\n"));
        assert!(result.ends_with("Line 2"));
    }

    #[test]
    fn test_cap_length_truncates_at_paragraph() {
        let content = "A".repeat(2000) + "\n\n" + &"B".repeat(100);
        let result = LiteratureNoteProcessor::cap_length(&content, 1500);

        assert!(result.len() < content.len());
        assert!(result.contains("[... truncated"));
    }

    #[test]
    fn test_cap_length_preserves_short_content() {
        let content = "Short content";
        let result = LiteratureNoteProcessor::cap_length(content, 1500);

        assert_eq!(result, content);
        assert!(!result.contains("truncated"));
    }

    #[test]
    fn test_validate_and_fix_adds_title_if_missing() {
        let content = "Just some text without headers";
        let result =
            LiteratureNoteProcessor::validate_and_fix(content, "My Source", "raw/source.md")
                .unwrap();

        assert!(result.contains("# My Source"));
    }
}
