use std::path::Path;

use chrono::Utc;

use crate::db::Database;
use crate::error::Result;
use crate::note::Note;

/// Generates and writes `index.md` for a grimoire vault.
///
/// The index is a navigable catalog of all notes in the vault, grouped by
/// note type with summary statistics. It is designed to be useful both for
/// humans browsing the vault and for LLM agents needing a map of the
/// knowledge base.
pub struct IndexGenerator<'a> {
    database: &'a Database,
}

/// The ordered list of note types to include in the index, with their
/// display names and DB type keys.
const NOTE_TYPE_SECTIONS: &[(&str, &str)] = &[
    ("Permanent Notes", "permanent"),
    ("Literature Notes", "literature"),
    ("Index Notes", "index"),
    ("Daily Notes", "daily"),
    ("Fleeting Notes", "fleeting"),
    ("Reference Notes", "reference"),
];

impl<'a> IndexGenerator<'a> {
    pub fn new(database: &'a Database) -> Self {
        Self { database }
    }

    /// Generate the full index.md content as a string.
    pub fn generate(&self) -> Result<String> {
        let total_notes = self.database.count_notes()?;
        let total_links = self.database.count_links()?;
        let type_counts = self.database.count_notes_by_type()?;
        let now = Utc::now().format("%Y-%m-%dT%H:%M:%SZ");

        let mut out = String::with_capacity(4096);

        // Header
        out.push_str("# Grimoire Index\n\n");
        out.push_str(&format!(
            "> Auto-generated by ztlgr. Last updated: {}\n",
            now
        ));
        out.push_str(&format!(
            "> Notes: {} | Links: {}\n",
            total_notes, total_links
        ));

        // Type breakdown in header
        if !type_counts.is_empty() {
            let breakdown: Vec<String> = type_counts
                .iter()
                .map(|(t, c)| format!("{}: {}", t, c))
                .collect();
            out.push_str(&format!("> Breakdown: {}\n", breakdown.join(", ")));
        }

        // Sections by note type
        for (section_name, type_key) in NOTE_TYPE_SECTIONS {
            let notes = self.database.list_notes_by_type(type_key, usize::MAX, 0)?;
            if notes.is_empty() {
                continue;
            }

            out.push('\n');
            out.push_str(&format!("## {}\n\n", section_name));

            for note in &notes {
                let entry = format_note_entry(note);
                out.push_str(&entry);
                out.push('\n');
            }
        }

        Ok(out)
    }

    /// Generate the index and write it to `index.md` in the vault root.
    pub fn write_index(&self, vault_path: &Path) -> Result<()> {
        let content = self.generate()?;
        let index_path = vault_path.join(".ztlgr").join("index.md");
        std::fs::write(&index_path, &content)?;
        tracing::info!("Wrote index to {}", index_path.display());
        Ok(())
    }
}

/// Format a single note entry for the index.
///
/// Format: `- [[Title]] -- first line of content (#type)`
fn format_note_entry(note: &Note) -> String {
    let summary = first_content_line(&note.content);
    let tags = note_tags_str(note);

    if summary.is_empty() && tags.is_empty() {
        format!("- [[{}]]", note.title)
    } else if summary.is_empty() {
        format!("- [[{}]] ({})", note.title, tags)
    } else if tags.is_empty() {
        format!("- [[{}]] -- {}", note.title, summary)
    } else {
        format!("- [[{}]] -- {} ({})", note.title, summary, tags)
    }
}

/// Extract the first non-empty, non-heading, non-frontmatter line from content.
fn first_content_line(content: &str) -> String {
    let mut in_frontmatter = false;

    for line in content.lines() {
        let trimmed = line.trim();

        // Skip YAML frontmatter
        if trimmed == "---" {
            in_frontmatter = !in_frontmatter;
            continue;
        }
        if in_frontmatter {
            continue;
        }

        // Skip empty lines
        if trimmed.is_empty() {
            continue;
        }

        // Skip markdown headings
        if trimmed.starts_with('#') {
            continue;
        }

        // Truncate to a reasonable length
        let max_len = 80;
        if trimmed.len() > max_len {
            return format!("{}...", &trimmed[..max_len]);
        }
        return trimmed.to_string();
    }

    String::new()
}

/// Build a short tag-like annotation for the note type.
fn note_tags_str(note: &Note) -> String {
    match &note.note_type {
        crate::note::NoteType::Literature { source } if !source.is_empty() => {
            format!("source: {}", source)
        }
        crate::note::NoteType::Reference { url: Some(url) } if !url.is_empty() => {
            format!("url: {}", url)
        }
        _ => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::note::{Metadata, NoteId, NoteType};
    use tempfile::TempDir;

    fn create_test_db() -> (Database, TempDir) {
        let temp_dir = TempDir::new().expect("Failed to create temp directory");
        let db_path = temp_dir.path().join("test.db");
        let db = Database::new(&db_path).expect("Failed to create test database");
        (db, temp_dir)
    }

    fn make_note(title: &str, content: &str, note_type: NoteType) -> Note {
        Note {
            id: NoteId::new(),
            title: title.to_string(),
            content: content.to_string(),
            note_type,
            zettel_id: None,
            parent_id: None,
            source: None,
            metadata: Metadata::default(),
            created_at: chrono::Utc::now(),
            updated_at: chrono::Utc::now(),
            deleted_at: None,
        }
    }

    // =====================================================================
    // format_note_entry tests
    // =====================================================================

    #[test]
    fn test_format_note_entry_basic() {
        let note = make_note(
            "Zettelkasten Method",
            "# Zettelkasten Method\n\nCore methodology for knowledge management",
            NoteType::Permanent,
        );
        let entry = format_note_entry(&note);
        assert_eq!(
            entry,
            "- [[Zettelkasten Method]] -- Core methodology for knowledge management"
        );
    }

    #[test]
    fn test_format_note_entry_empty_content() {
        let note = make_note("Empty Note", "", NoteType::Permanent);
        let entry = format_note_entry(&note);
        assert_eq!(entry, "- [[Empty Note]]");
    }

    #[test]
    fn test_format_note_entry_only_heading() {
        let note = make_note("Just Title", "# Just Title\n\n", NoteType::Permanent);
        let entry = format_note_entry(&note);
        assert_eq!(entry, "- [[Just Title]]");
    }

    #[test]
    fn test_format_note_entry_with_literature_source() {
        let note = make_note(
            "Ahrens2017",
            "# Ahrens2017\n\nSummary of How to Take Smart Notes",
            NoteType::Literature {
                source: "raw/ahrens-2017.md".to_string(),
            },
        );
        let entry = format_note_entry(&note);
        assert!(entry.contains("(source: raw/ahrens-2017.md)"));
    }

    #[test]
    fn test_format_note_entry_with_reference_url() {
        let note = make_note(
            "Rust Book",
            "# Rust Book\n\nThe Rust Programming Language book",
            NoteType::Reference {
                url: Some("https://doc.rust-lang.org/book/".to_string()),
            },
        );
        let entry = format_note_entry(&note);
        assert!(entry.contains("(url: https://doc.rust-lang.org/book/)"));
    }

    #[test]
    fn test_format_note_entry_truncates_long_lines() {
        let long_line = "A".repeat(120);
        let content = format!("# Title\n\n{}", long_line);
        let note = make_note("Long Note", &content, NoteType::Permanent);
        let entry = format_note_entry(&note);
        assert!(entry.contains("..."));
        // 80 chars + "..." = truncated
        assert!(entry.len() < 130);
    }

    #[test]
    fn test_format_note_entry_skips_frontmatter() {
        let content = "---\ntitle: Test\ntags: [foo]\n---\n\n# Test\n\nActual content here";
        let note = make_note("Test", content, NoteType::Permanent);
        let entry = format_note_entry(&note);
        assert_eq!(entry, "- [[Test]] -- Actual content here");
    }

    // =====================================================================
    // first_content_line tests
    // =====================================================================

    #[test]
    fn test_first_content_line_empty() {
        assert_eq!(first_content_line(""), "");
    }

    #[test]
    fn test_first_content_line_only_headings() {
        assert_eq!(first_content_line("# Title\n## Subtitle"), "");
    }

    #[test]
    fn test_first_content_line_with_frontmatter() {
        let content = "---\ntitle: Foo\n---\n\nContent line";
        assert_eq!(first_content_line(content), "Content line");
    }

    #[test]
    fn test_first_content_line_normal() {
        assert_eq!(
            first_content_line("# Heading\n\nFirst real line"),
            "First real line"
        );
    }

    // =====================================================================
    // IndexGenerator.generate() integration tests
    // =====================================================================

    #[test]
    fn test_generate_empty_vault() {
        let (db, _temp) = create_test_db();
        let gen = IndexGenerator::new(&db);

        let content = gen.generate().expect("Failed to generate");

        assert!(content.starts_with("# Grimoire Index\n"));
        assert!(content.contains("Notes: 0 | Links: 0"));
        // No sections since there are no notes
        assert!(!content.contains("## Permanent Notes"));
    }

    #[test]
    fn test_generate_with_notes() {
        let (db, _temp) = create_test_db();

        db.create_note(&make_note(
            "Zettelkasten",
            "# Zettelkasten\n\nCore method",
            NoteType::Permanent,
        ))
        .expect("Failed");

        db.create_note(&make_note(
            "Quick Idea",
            "# Quick Idea\n\nSomething fleeting",
            NoteType::Fleeting,
        ))
        .expect("Failed");

        let gen = IndexGenerator::new(&db);
        let content = gen.generate().expect("Failed to generate");

        assert!(content.contains("Notes: 2 | Links: 0"));
        assert!(content.contains("## Permanent Notes"));
        assert!(content.contains("- [[Zettelkasten]] -- Core method"));
        assert!(content.contains("## Fleeting Notes"));
        assert!(content.contains("- [[Quick Idea]] -- Something fleeting"));
    }

    #[test]
    fn test_generate_sections_in_correct_order() {
        let (db, _temp) = create_test_db();

        // Create one note of each type to test ordering
        db.create_note(&make_note("P", "# P\n\nPermanent", NoteType::Permanent))
            .expect("Failed");
        db.create_note(&make_note(
            "L",
            "# L\n\nLit",
            NoteType::Literature {
                source: "".to_string(),
            },
        ))
        .expect("Failed");
        db.create_note(&make_note("I", "# I\n\nIndex", NoteType::Index))
            .expect("Failed");
        db.create_note(&make_note("D", "# D\n\nDaily", NoteType::Daily))
            .expect("Failed");
        db.create_note(&make_note("F", "# F\n\nFleeting", NoteType::Fleeting))
            .expect("Failed");
        db.create_note(&make_note(
            "R",
            "# R\n\nRef",
            NoteType::Reference { url: None },
        ))
        .expect("Failed");

        let gen = IndexGenerator::new(&db);
        let content = gen.generate().expect("Failed to generate");

        // Sections should appear in this order
        let pos_permanent = content.find("## Permanent Notes").unwrap();
        let pos_literature = content.find("## Literature Notes").unwrap();
        let pos_index = content.find("## Index Notes").unwrap();
        let pos_daily = content.find("## Daily Notes").unwrap();
        let pos_fleeting = content.find("## Fleeting Notes").unwrap();
        let pos_reference = content.find("## Reference Notes").unwrap();

        assert!(pos_permanent < pos_literature);
        assert!(pos_literature < pos_index);
        assert!(pos_index < pos_daily);
        assert!(pos_daily < pos_fleeting);
        assert!(pos_fleeting < pos_reference);
    }

    #[test]
    fn test_generate_excludes_deleted_notes() {
        let (db, _temp) = create_test_db();

        let id = db
            .create_note(&make_note("Deleted", "Content", NoteType::Permanent))
            .expect("Failed");
        db.create_note(&make_note("Active", "Content", NoteType::Permanent))
            .expect("Failed");
        db.delete_note(&id).expect("Failed");

        let gen = IndexGenerator::new(&db);
        let content = gen.generate().expect("Failed to generate");

        assert!(content.contains("Notes: 1"));
        assert!(!content.contains("Deleted"));
        assert!(content.contains("Active"));
    }

    #[test]
    fn test_generate_includes_link_count() {
        let (db, _temp) = create_test_db();

        let id_a = db
            .create_note(&make_note("A", "Content", NoteType::Permanent))
            .expect("Failed");
        let id_b = db
            .create_note(&make_note("B", "Content", NoteType::Permanent))
            .expect("Failed");
        db.create_link(&id_a, &id_b, "reference", None)
            .expect("Failed");

        let gen = IndexGenerator::new(&db);
        let content = gen.generate().expect("Failed to generate");

        assert!(content.contains("Notes: 2 | Links: 1"));
    }

    #[test]
    fn test_generate_includes_type_breakdown() {
        let (db, _temp) = create_test_db();

        db.create_note(&make_note("P1", "Content", NoteType::Permanent))
            .expect("Failed");
        db.create_note(&make_note("P2", "Content", NoteType::Permanent))
            .expect("Failed");
        db.create_note(&make_note("D1", "Content", NoteType::Daily))
            .expect("Failed");

        let gen = IndexGenerator::new(&db);
        let content = gen.generate().expect("Failed to generate");

        assert!(content.contains("> Breakdown:"));
        assert!(content.contains("permanent: 2"));
        assert!(content.contains("daily: 1"));
    }

    #[test]
    fn test_generate_notes_alphabetically_within_section() {
        let (db, _temp) = create_test_db();

        db.create_note(&make_note("Zebra", "# Zebra\n\nZ", NoteType::Permanent))
            .expect("Failed");
        db.create_note(&make_note("Alpha", "# Alpha\n\nA", NoteType::Permanent))
            .expect("Failed");

        let gen = IndexGenerator::new(&db);
        let content = gen.generate().expect("Failed to generate");

        let pos_alpha = content.find("[[Alpha]]").unwrap();
        let pos_zebra = content.find("[[Zebra]]").unwrap();
        assert!(pos_alpha < pos_zebra);
    }

    #[test]
    fn test_generate_skips_empty_sections() {
        let (db, _temp) = create_test_db();

        db.create_note(&make_note("P", "Content", NoteType::Permanent))
            .expect("Failed");

        let gen = IndexGenerator::new(&db);
        let content = gen.generate().expect("Failed to generate");

        // Only Permanent section should appear
        assert!(content.contains("## Permanent Notes"));
        assert!(!content.contains("## Literature Notes"));
        assert!(!content.contains("## Index Notes"));
        assert!(!content.contains("## Daily Notes"));
        assert!(!content.contains("## Fleeting Notes"));
        assert!(!content.contains("## Reference Notes"));
    }

    // =====================================================================
    // write_index test
    // =====================================================================

    #[test]
    fn test_write_index_creates_file() {
        let (db, _temp) = create_test_db();

        db.create_note(&make_note("Test", "Content", NoteType::Permanent))
            .expect("Failed");

        // Create the .ztlgr dir (normally done by Vault::initialize)
        let vault_path = _temp.path();
        std::fs::create_dir_all(vault_path.join(".ztlgr")).unwrap();

        let gen = IndexGenerator::new(&db);
        gen.write_index(vault_path).expect("Failed to write index");

        let index_path = vault_path.join(".ztlgr").join("index.md");
        assert!(index_path.exists());

        let content = std::fs::read_to_string(index_path).unwrap();
        assert!(content.contains("# Grimoire Index"));
        assert!(content.contains("[[Test]]"));
    }
}
